### ISSUE TITLE
Connect now ships with CSRF middleware

### ISSUE THREAD

**Issue by kkaefer** [developmentseed/bones#15]
This causes a crash:

```

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot set property csrf of #<Object> which has only a getter
    at Object.<anonymous> (/Users/kkaefer/node_modules/tilestream/node_modules/bones/server/middleware.js:39:17)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/Users/kkaefer/node_modules/tilestream/node_modules/bones/bones.js:11:22)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
```

**Comment by kkaefer** [comment]
Fixed in 63d3825791005d599ccb32f5707faff0a4046393
