### ISSUE TITLE
TypeError: Cannot set property csrf of [object Object] which has only a getter

### ISSUE THREAD

**Issue by alduro** [developmentseed/bones#16]
after update express I got this error on bones application startup:

TypeError: Cannot set property csrf of #<Object> which has only a getter
    at Object.<anonymous> (/Users/aldo/Satio/Desarrollo/express/satio-bones/node_modules/bones/server/middleware.js:39:17)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/Users/aldo/Satio/Desarrollo/express/satio-bones/node_modules/bones/bones.js:11:22)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)

Checking middleware.js file I found csrf is being set when only get is allowed.

39 exports['csrf'] = function csrf() {
...
}

aldo@macbook ~/Satio/Desarrollo/express/satio-bones/node_modules/bones/node_modules/express > node

> exports = module.exports = require('express');
> { basicAuth: [Getter],
>   bodyParser: [Getter],
>   compiler: [Getter],
>   cookieParser: [Getter],
>   csrf: [Getter],
>   version: '2.4.2',

**Comment by alduro** [comment]
sorry, it was fixed in issue #15.
