### ISSUE TITLE
Node 0.6 Works but gives a warning.

### ISSUE THREAD

**Issue by KeyvanJS** [developmentseed/bones#32]
The "sys" module is now called "util". It should have a similar interface.

**Comment by springmeyer** [comment]
node v6 did not work for me. I saw:

```

~/projects/tilemill[node-v6]$ ./index.js 
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: Invalid flags supplied to RegExp constructor 'is'
    at new RegExp (unknown source)
    at Object.browserAugmentation (/Users/dane/projects/tilemill/node_modules/bones/node_modules/jquery/node_modules/jsdom/lib/jsdom/browser/index.js:345:1)
    at Object.jsdom (/Users/dane/projects/tilemill/node_modules/bones/node_modules/jquery/node_modules/jsdom/lib/jsdom.js:11:26)
    at create (/Users/dane/projects/tilemill/node_modules/bones/node_modules/jquery/dist/node-jquery.js:5:39)
    at /Users/dane/projects/tilemill/node_modules/bones/node_modules/jquery/dist/node-jquery.js:8333:18
    at Object.<anonymous> (/Users/dane/projects/tilemill/node_modules/bones/node_modules/jquery/dist/node-jquery.js:8337:1)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
```

which I could work around by installing at the top level a more recent version of jsdom

**Comment by springmeyer** [comment]
these are the versions I installed _before_ bones that allowed things to work: https://github.com/mapbox/tilemill/blob/node-v6/package.json#L24-25

**Comment by springmeyer** [comment]
closing, new ticket to trac things at #47
