### ISSUE TITLE
support node v6 in 1.3 branch

### ISSUE THREAD

**Issue by springmeyer** [developmentseed/bones#47]
This is needed for TileMill, since TileMill does not yet use bones 2.x.

This commit (https://github.com/developmentseed/bones/commit/3e3a0b6fdd2720ab92cd0eb6b2d771ab69627c9b) was all that was needed since the latest express 2.x supports both node v4 and node v6.

Tests pass before and after this change with node v0.4.12 and after with node v.0.6.11.

Although we have a new warning with node v0.6.11:

```

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at [object Object].<anonymous> (events.js:139:15)
    at [object Object].once (events.js:160:8)
    at [object Object].listen (net.js:775:10)
    at Function.response (/usr/local/lib/node_modules/expresso/bin/expresso:424:16)
    at Test.fn (/Users/dane/projects/tilemill/node_modules/bones/test/collections.test.js:15:12)
    at Test.runParallel (/usr/local/lib/node_modules/expresso/bin/expresso:959:10)
    at Test.run (/usr/local/lib/node_modules/expresso/bin/expresso:924:18)
    at next (/usr/local/lib/node_modules/expresso/bin/expresso:867:22)
    at runSuite (/usr/local/lib/node_modules/expresso/bin/expresso:875:6)
    at check (/usr/local/lib/node_modules/expresso/bin/expresso:814:12)
```

**Comment by yhahn** [comment]
This looks good to go. I will confirm with @willwhite tomorrow -- then all that's needed is for this to be rolled into a tag?

**Comment by springmeyer** [comment]
this is now tagged in v1.3.24. closing.
